### PR TITLE
Added columns and rows!

### PR DESCRIPTION
**Pull request by Swanarog**
the static horizontal layout is terrible....
Also adjusted button sizes, when blizzard textures are disabled.

### CODE REVIEW

**Comment by Tuller** [comment]
The extra ability bar could have abilities appear in combat that's the tricky bit to handle

**Comment by Swanarog** [comment]
That is why I included the QueueLayoutUpdate function. it' be the only way to handle it, short of recreating the buttons from scratch.

**Comment by Tuller** [comment]
So here's what I'm specifically thinking of as a scenario:
* You enter combat, the ExtraAbilityContainer has nothing on it
* During combat, an event triggers and adds a new ability to the ExtraAbilityContainer

I don't think that we can handle that properly.

**Comment by Swanarog** [comment]
with this: 	hooksecurefunc(ExtraAbilityContainer, "LayoutChildren", function() bar:QueueLayoutUpdate() end)

If that scenario happens, the update is queued, as soon as combats ends, a Layout call is made. Nothing can be updated in combat, but can be cleaned as soon as combat ends.

I'll be using it in my own UI, just thought I'd share, if you wanted to use it.

**Comment by Tuller** [comment]
Yeah I just mean because of that the button won't show up until exiting combat and thus won't be visible to the user.

**Comment by Swanarog** [comment]
Actually, I think it'd be displayed where blizzard designed, but after
combat would be relocated to the dominos bar.

**Pull request closed without merging**
