### PR TITLE
Nudge upgrade

### PR DESCRIPTION
**Pull request by Goranaws**
Allow frames to be nudged with movement keys by various amounts, for higher precision.

### CODE REVIEW

**Comment by Tuller** [comment]
The one thing I want to add to the keyboard movement stuff is holding the key to start auto repeating the movement operation (hold for 500ms, repeat every 50ms?)

I've also for some reason contemplated the following:
* Tab cycling between frames (top left to bottom right, front to back)
* Space to open the menu when a bar is focused
* Tab cycling between all of the options on the interface, plus escape to close (if the window is focused but not an input)

**Comment by Goranaws** [comment]
In order to add continuous, or repeated movement, we will need to introduce an update function when a key is press and held. most likely this would begin on key down, and then if a corresponding on key up is not detected, it would start nudging the frame every few milliseconds.

**Comment by Goranaws** [comment]
Tab cycling through frames, maybe tricky. In order to sequence through the frames from top left of the screen, towards bottom left (typewriter style), we would need to sort the frames by their position on screen. Which would mean collecting all positions and dimensions from each drag frame, then sorting through them in an intelligent manner.  We would also want to include frame layering information, for stacked frames...

**Comment by Goranaws** [comment]
I believe some of the functions on the following WoW file might be very relevant to this and some our other recent updates.

https://github.com/Goranaws/SecureHoverDriver.lua/blob/main/SecureHoverDriver.lua

**Comment by Tuller** [comment]
Honestly I wouldn’t worry about tab cycling yet.

**Comment by Goranaws** [comment]
I've just uploaded more adjustments. I'm going to leave things be with this for now, till you have a chance to look.

**Comment by Goranaws** [comment]
Just posted an update for active nudge

**Pull request closed without merging**
