### PR TITLE
Snap to grid

### PR DESCRIPTION
**Pull request by Swanarog**
keep track of the lines, for easier grid snapping

### CODE REVIEW

**Comment by Swanarog** [comment]
I'm wondering if the enhanced snapping features for stick to edge and grid snapping should be part of FlyPaper now.

**Comment by Tuller** [comment]
How does this compare to this branch? https://github.com/tullamods/Dominos/tree/snap-to-grid

**Comment by Swanarog** [comment]
The end results are the same, but mine prioritizes the corner nearest to the cursor. so if you drag a frame near it's corner, it will prioritize that corner for grid snapping. This is useful if more than one corner of a frame is within grid snapping distance. 

I'll see if can integrate that concept into your implementation.

**Comment by Tuller** [comment]
I've added a few things in my branch, though there's still a bit more work to do. I expect something like this could be extracted cleanly into a different library

```lua
-- getting the closest point to your cursor's position
local point, distance = Lib:GetNearestPointToCursor(frame)

-- snapping to frames
local point, relPoint, x, y, distance = Lib:GetNearestAnchorPoint(frame, relFrame, [point])

-- snapping to grid on a containing frame
local point, relPoint, x, y, distance = Lib:GetNearestPointOnGrid(frame, relFrame, scale)

-- snapping to edges on a containing frame
local point, relPoint, x, y, distance = Lib::GetNearestRelativePoint(frame, relFrame, [onlySamePoints])
```

**Comment by Tuller** [comment]
I also want to reiterate that I like the changes :)

**Comment by Swanarog** [comment]
Got this working in your latest branch. 
https://github.com/Swanarog/Dominos/blob/master/Dominos/core/frame.lua

**Comment by Swanarog** [comment]
Just occurred to me that we need to disable grid snapping when the grid is not shown.

**Comment by Tuller** [comment]
Yep, on my list.

**Comment by Tuller** [comment]
I have that implemented in the latest commit. I also ended up trying to move most of the positioning logic into the 2.0 version of flypaper.
https://github.com/Tuller/FlyPaper-2.0

The biggest difference in design is that FlyPaper will tell you the nearest points now, but it won't actually do the positioning itself.

**Comment by Goranaws** [comment]
I'm always surprised by how you are able to decipher my code.. I know I don't write things super clear, but i know I've got some good ideas. I'm glad you are able to make sense of it all.

**Comment by Swanarog** [comment]
the use of Frame:Get here: https://github.com/tullamods/Dominos/blob/master/Dominos/core/frame.lua#L768 does not account for non-Dominos frames. I'm trying test your flypaper 2.0 with one of my ow addons, but i think the method used here creates a disconnect..

**Comment by Tuller** [comment]
It should probably be frame:get or flypaper get

**Comment by Swanarog** [comment]
this: https://github.com/tullamods/Dominos/compare/master...Swanarog:patch-3

**Comment by Tuller** [comment]
Yep pretty much that

**Comment by Swanarog** [comment]
I want to let you know that I have begun building my own core addon. I'm not sure how long it will take to complete, but I hope to begin weening my addons off of Dominos soon, and I'm glad I'll be able to retain bar snapping compatibility with Dominos! I appreciate having been able to work with Dominos for so long. Thank you!

And I really think this new version of FlyPaper could greatly enhance UI customization and design! I hope to see more authors start using it in their addons.

**Pull request merged**
